### ISSUE TITLE
Start PoA network with "additional" authorities beyond the initial list

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity-deploy#2]
This would help testing PoA networks where the set of authorities will transition at an expected time

**Comment by ddorgan** [comment]
Hi Rob,
       Thanks for raising this, I'll need to do two things on this: 

1) Maybe change it so you can have a more fine grained input config file.
2) Update the README.md and put more info there.

But for now, if you say wanted to spin up a few authority nodes and maybe have additional authorities, if you edit the file: parity-deploy/config/spec/engine/aura and edit:

"list": [ 0x0000000000000000000000000000000000000000 ]

Could you just add them there? e.g. something like:

"list": [ 0x0000000000000000000000000000000000000000 , 0xAAAAA, 0xBBBBB ]

And then have other nodes connect to this docker instance being AAAA, BBBB etc.. ? Or is this view too simplistic?

Thanks,
David

**Comment by rphmeier** [comment]
Changing the fixed list once the chain has launched will lead to errors further on. We usually do transitions via a "multi" set that switches lists/contracts based on block number. so something like
```json
"multi": {
    "0": { "list": [ 0x0000000000000000000000000000000000000000 ] },
    "100": { "list": [ 0x0000000000000000000000000000000000000000 , 0xAAAAA, 0xBBBBB ] }
}
```

**Comment by ddorgan** [comment]
Hi Robert,
           Thanks for explaining, will look into this. I know it's a bit hacky but as mentioned can you not just paste that whole thing into config/spec/engine/aura:

e.g. before:
Before:

        "engine": {
        "authorityRound": {
            "params": {
                "gasLimitBoundDivisor": "0x400",
                "stepDuration": "5",
                "multi": {
                "0": { "list": [ 0x0000000000000000000000000000000000000000 ] },
                "100": { "list": [ 0x0000000000000000000000000000000000000000 , 0xAAAAA, 0xBBBBB ] }
                }

            }
        }
    },

And then run say: ./parity-deploy.sh --name testing --engine aura --nodes 1 and look at the output file deployment/chain/spec.json you should see:

{

        "name": "testing",
        "engine": {
        "authorityRound": {
            "params": {
                "gasLimitBoundDivisor": "0x400",
                "stepDuration": "5",
                "multi": {
                "0": { "list": [ "0x859d9ae0829f2ed587f20bca370832243302169d" ] },
                "100": { "list": [ "0x859d9ae0829f2ed587f20bca370832243302169d" , 0xAAAAA, 0xBBBBB ] }
                }

            }
        }
    },


Thanks,
David

**Comment by ddorgan** [comment]
Sorry this is assuming you already have the keys for 0xAAAA, 0xBBBB and would connect some test nodes manually later using the whole new spec.json and say a reserved-peers file to point at the docker instance.

Thanks,
David

**Comment by ddorgan** [comment]
Hi Rob,
      Does this https://github.com/paritytech/parity-deploy/pull/19 help? You can put all the custom chain info into one file and have this build the docker configuration.
David

**Comment by rphmeier** [comment]
could you describe how it helps with this issue? being able to generate multi-transitions and authority configurations for each address contained within the multi-set's children is more what we need. 

This would be especially nice if contract templates were integrated, so it could create node configuration from the contract's initial list. Further on, we could have parity-deploy create a node configuration for an address _not specifically mentioned_ in any of the validator sets, so we can easily create setups for authorities who are added only via a contract.

**Comment by keorn** [comment]
Right now this is done the other way. Similar to test RPC, where Parity Deploy comes with a bunch of pre-specified addresses which you can use to write your contracts and specs.
