### ISSUE TITLE
There was an error reading your config file at: /parity/authority.toml

### ISSUE THREAD

**Issue by daverod24** [paritytech/parity-deploy#24]
## trying to set   

```./parity-deploy.sh --config aura --nodes 2 --name test``` 
![image](https://user-images.githubusercontent.com/981954/30083068-ae4a40d0-9252-11e7-975c-6c87820ac928.png)

## This is my configuration but being original also gives error
![image](https://user-images.githubusercontent.com/981954/30083054-a10090a0-9252-11e7-961b-ec927c360eb3.png)

## the configuration throws two errors:

![image](https://user-images.githubusercontent.com/981954/30083091-c6a2c0a8-9252-11e7-8e0a-8994f13640c9.png)

# what can be done to solve ??

**Comment by ddorgan** [comment]
Hi there,
          Could you run this and check if it helps? Just execute:

```rm -rf deployment && ./parity-deploy.sh --config aura --nodes 2 --name test```

Let me know if this helps...

**Comment by daverod24** [comment]
the same problem is not fixed.

it says that it is not a file I was reviewing as I can fix it I mount it separately as a volume in a busybox and mount the file perfectly but I do not know what I can do

**Comment by daverod24** [comment]
@ddorgan  how to deploy  aura?? 

I made git clone on another pc and try

`` `git clone https://github.com/paritytech/parity-deploy.git` ``

then

`` `./parity-deploy.sh --config aura --nodes 2 --name test` ``

and I get the same error

**Comment by daverod24** [comment]
cuando hago deploy  en dev

```./parity-deploy.sh --config dev --name test```

trabaja bien

**Comment by ddorgan** [comment]
Which distro are you using? And what version?
Also could you maybe tar up the parity-deploy dir and make it available so I can take a look. 
I sometimes get this if I'm using lots of different configs, but when I ```rm -rf data deployment docker-compose.yml ``` and re-run parity-deploy.sh it works.

**Comment by daverod24** [comment]
I tested it in two distros
Linux drodrila-ever 4.9.47-1-MANJARO # 1 SMP PREEMPT Sat Sep 2 07:29:38 UTC 2017 x86_64 GNU / Linux
and also
Linux testing 4.9.0-3-amd64 # 1 SMP Debian 4.9.30-2 + deb9u2 (2017-06-26) x86_64 GNU / Linux

I'm going to prove what you tell me and I'll tell you

**Comment by daverod24** [comment]
I do not know what I did but erased everything I made git clone
  and then I did your steps and now is running in local

![image](https://user-images.githubusercontent.com/981954/30126238-fe718038-9300-11e7-9a80-5bbcc990e13d.png)

I am missing a test to see if I run in azure container services that I need it there with swarm
I was going to ask you how to make the volumes were in azure storage.?

I did something like that
![image](https://user-images.githubusercontent.com/981954/30126375-6749af90-9301-11e7-9cb7-b9765f8ae934.png)


  I'll try using kubernetes

**Comment by ddorgan** [comment]
I'm not 100% sure on the azure storage, but once docker-compose can talk to the backend and it's listed, it should just work. I've only ever tried this with kubernetes myself.

Can this issue be closed?

**Comment by daverod24** [comment]
the problem persists when I want to have the files in swarm in azure!

in local on my machine if nodes work perfectly

I try to do this for the data to take from my volume of swarm

```docker cp deployment / storageazure: / deployment```

after

I add the volumes in docker-compose and I get the errors of not finding the file of authority.toml
try several configurations, it will be that somehow you can improve that volume management
example this:
```
    volumes:
       - ./deployment/chain/spec.json:/parity/spec.json
       - ./deployment/chain/reserved_peers:/parity/reserved_peers
       - ./deployment/1/password:/parity/password
       - ./deployment/1/authority.toml:/parity/authority.toml
       - ./deployment/1/${NETWORK_NAME}:/parity/data/keys/${NETWORK_NAME}
       - ./data/1:/parity/data
```
to this that by the way I try but does not take that conf, and gives me the same error:
```
    volumes:
       - namedvolumeforexample/deployment/chain/:/parity/
       - ./deployment/1/:/parity/
       - ./deployment/1/${NETWORK_NAME}:/parity/data/keys/${NETWORK_NAME}
       - ./data/1:/parity/data
```

these were the tests last night
![image](https://user-images.githubusercontent.com/981954/30184315-5c5e6ade-93e3-11e7-9344-0c550d72200a.png)

![image](https://user-images.githubusercontent.com/981954/30184324-689a1d3e-93e3-11e7-8f38-3e3b1b498408.png)



![image](https://user-images.githubusercontent.com/981954/30183911-c6a8f366-93e1-11e7-85df-22bdf3dab2a5.png)

**Comment by ddorgan** [comment]
Hi there,
        As mentioned before, any  chance you could tar up the whole directory and put it somewhere so I can take a look. Just want to 1) double check the config and 2) use the same swarm settings.

The actual files are a more useful than screenshots.

Thanks!
