### ISSUE TITLE
Download only once

### ISSUE THREAD

**Issue by keorn** [paritytech/parity-deploy#26]
Especially ethstats takes pretty long to get for multiple nodes, though then setup is more single machine specific.

**Comment by ddorgan** [comment]
Hi Peter,
         Can you re-try running it again. Do you see it re-download ethstats? Docker should only do this once, once you don't wipe your docker images. It does take a while, they're over 1.3g in size combined:

buythewhale/ethstats_monitor   latest              5adf546983cd        5 months ago        477.2 MB
buythewhale/ethstats           latest              9019cb3b4556        5 months ago        899.8 MB

**Comment by keorn** [comment]
True
