### ISSUE TITLE
Does not work at all on OSX

### ISSUE THREAD

**Issue by roderik** [paritytech/parity-deploy#38]
I was trying to generate a new docker config on OSX, but it does not work at all:

* parity is installed by homebrew, but `if [ ! -f /usr/bin/parity ] || [ ! "$PARITY_RELEASE" == "" ] ; then` is not the correct check since it reisdes in `/usr/local/bin/parity`. The oneline installer tries to do something funky with the keychain and then fails.

* sed on OSX is not gnu sed. 

```
sed: 1: "config/spec/example.spec": command c expects \ followed by text
sed: 1: "config/spec/example.spec": command c expects \ followed by text
sed: 1: "docker-compose.yml": extra characters at the end of d command
```

**Comment by froid1911** [comment]
Same here, on Ubuntu its working :-(

**Comment by ddorgan** [comment]
Hi there, parity-deploy is currently only supports linux as the base o/s I'm afraid...
