### ISSUE TITLE
Client node is not added to the `reserved_peers` list

### ISSUE THREAD

**Issue by 0x7CFE** [paritytech/parity-deploy#39]
When client node is created using `--enable-client` looks like it is not added to the `reserved_peers` list. If `--reserved-only` option is passed it results in nodes not seeing each other.

I don't quite understand why client node is not set as reserved. Is there some reasoning for it?

**Comment by ddorgan** [comment]
@0x7CFE yes as the client only needs to connect to the authorities rather than needing the authorities connect to it. Agreed? Can this be closed?
