### ISSUE TITLE
Test transaction corpora

### ISSUE THREAD

**Issue by keorn** [paritytech/parity-deploy#4]
Generate files with json arrays of the following RPC objects:
- [x] zero value tx from account to 0: eth, personal
- [x] presigned zero value tx from account to itself
- [ ] presigned zero value tx from multiple accounts
- [ ] realistic public net txs
- [ ] contract deployments
- [ ] skipped nonce

**Comment by keorn** [comment]
https://drive.google.com/drive/folders/0B8F2pjh7CQ9vREM5TGNEOC1fS1U?usp=sharing

**Comment by ddorgan** [comment]
Resolved and files links in the README.md
