### ISSUE TITLE
Parity dashboard works only partially

### ISSUE THREAD

**Issue by gmile** [paritytech/parity-deploy#41]
I've just installed parity on a VM instance in Google, and I can't seem to get fully working. It's somewhat partially working though.

![image](https://user-images.githubusercontent.com/207112/36435726-1ce12c92-166b-11e8-8644-b1971e8be50f.png)
(the ip on the screenshot is fake)

Note the red path to config in the top right – does this indicate something is wrong?

I've made sure these ports are exposed publicly (without them the entire thing would not be available at all):
![image](https://user-images.githubusercontent.com/207112/36435897-8a0a5122-166b-11e8-904f-e89dbf68b2a0.png)

My parity version is **v1.9.2-beta-b60511e-20180214**/x86_64-linux-gnu/rustc1.23.0.

Am I not configuring some things right? From looking at the `client` server logs by means of `docker-compose -f logs`, I can't see anything suspicious.

**Comment by ddorgan** [comment]
Can you try using something like this to connect to the host and see if it helps?

```
ssh -L 8180:localhost:8180 -L 8545:localhost:8545 -L 8546:localhost:8545 user@remote-host
```

Then try and connect to http://localhost:8180/

**Comment by ddorgan** [comment]
Hi there, basically you would need to login to the system and execute parity signer new-token in order to get a token. Or else run it with --clients and use docker-compose logs and check for the UI token there.

**Comment by gmile** [comment]
Hi @ddorgan I did that back when I was making the screenshots above. As you can see, one of the screenshots has the code in it (black text on dark grey background.

So I was unable to fix the issue with UI, but the API is working and that was what I need from the start... so I don't know, I guess we can close the issue.
