### ISSUE TITLE
invalid type: string "all", expected a sequence for key `rpc.cors`

### ISSUE THREAD

**Issue by mengjiaqi** [paritytech/parity-deploy#42]
when i start parity with parity-deploy project, it shows me 
```
Loading config file from /parity/authority.toml
You might have supplied invalid parameters in config file.
invalid type: string "all", expected a sequence for key `rpc.cors`
```
and, the commands i used ware
```shell
./parity-deploy.sh --config aura
docker-compose up
```

**Comment by mengjiaqi** [comment]
this error only find in version v1.9.* & beta.
when i run it with version v1.8.11 & stable, it works well

**Comment by ddorgan** [comment]
Yes, this options seems to have changed between 1.8 and 1.9 ... i'll make an update.

**Comment by ddorgan** [comment]
Can you please try now after https://github.com/paritytech/parity-deploy/commit/792912be2ef784f1ade6c79f4d436257152dec57

**Comment by mengjiaqi** [comment]
@ddorgan OK, i'll try it and share the resoult

**Comment by ddorgan** [comment]
@mengjiaqi any update on this?

**Comment by ddorgan** [comment]
Resolved with https://github.com/paritytech/parity-deploy/commit/792912be2ef784f1ade6c79f4d436257152dec57 .. no reply, closing ticket.
