### ISSUE TITLE
Running docker-compose logs returns no token

### ISSUE THREAD

**Issue by crossoveranx** [paritytech/parity-deploy#49]
Currently trying to utilize this parity repo with a PoA chain and I can't seem to get an appropriate account that is funded. I am trying to open the UI with SSH'ed into a remote node. I have tried the | grep token option, but it returns nothing from the logs. When I go to inspect the logs manually, I don't see any token generated:

host2    | Loading config file from /parity/authority.toml
host2    | 2018-08-16 13:21:18 UTC Starting Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
host2    | 2018-08-16 13:21:18 UTC Keys path /parity/data/keys/MPDL
host2    | 2018-08-16 13:21:18 UTC DB path /parity/data/chains/MPDL/db/0796728f28a12423
host2    | 2018-08-16 13:21:18 UTC State DB configuration: fast
host2    | 2018-08-16 13:21:18 UTC Operating mode: active
host2    | 2018-08-16 13:21:18 UTC Configured for MPDL using AuthorityRound engine
host2    | 2018-08-16 13:21:23 UTC Public node URL: enode://49accab3db8be0bae061f3e160420b15e6b0509b44fa287bcf5d18f4f6c5a9c3c960edd31561af4747b88cdb6d491f4a40ddb84b55bfa44b29dbc5c38ed64c39@172.18.0.4:30303
host2    | 2018-08-16 13:21:53 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:22:23 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:22:53 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | Loading config file from /parity/authority.toml
host3    | 2018-08-16 13:21:18 UTC Starting Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
host3    | 2018-08-16 13:21:18 UTC Keys path /parity/data/keys/MPDL
host3    | 2018-08-16 13:21:18 UTC DB path /parity/data/chains/MPDL/db/0796728f28a12423
host3    | 2018-08-16 13:21:18 UTC State DB configuration: fast
host3    | 2018-08-16 13:21:18 UTC Operating mode: active
host3    | 2018-08-16 13:21:18 UTC Configured for MPDL using AuthorityRound engine
host3    | 2018-08-16 13:21:23 UTC Public node URL: enode://57e3319313cd966a95e5a3f73b7f4954f88693ac36b7e4a46525dde705fe7aaa5be2e6736d60190e3289591f0c68916c887d675d2acb4ac10e8f500aea26b9f6@172.18.0.3:30303
host3    | 2018-08-16 13:21:53 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | 2018-08-16 13:22:23 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | 2018-08-16 13:22:53 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | Loading config file from /parity/authority.toml
host1    | 2018-08-16 13:21:19 UTC Starting Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
host1    | 2018-08-16 13:21:19 UTC Keys path /parity/data/keys/MPDL
host1    | 2018-08-16 13:21:19 UTC DB path /parity/data/chains/MPDL/db/0796728f28a12423
host1    | 2018-08-16 13:21:19 UTC State DB configuration: fast
host1    | 2018-08-16 13:21:19 UTC Operating mode: active
host1    | 2018-08-16 13:21:19 UTC Configured for MPDL using AuthorityRound engine
host1    | 2018-08-16 13:21:24 UTC Public node URL: enode://70f471330433ff3ab8d9461e00899d1be6b11c4c178f627d90d5a4b836e9fdbd27f1ab66a5bec5b335c189fabeeca819acf9baeff303af70b2a48b814ce2000d@172.18.0.2:30303
host1    | 2018-08-16 13:21:49 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:22:19 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:22:49 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
lawton@vm65:~/parity-deploy$ docker-compose logs -f
Attaching to host2, host3, host1
host2    | Loading config file from /parity/authority.toml
host2    | 2018-08-16 13:21:18 UTC Starting Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
host2    | 2018-08-16 13:21:18 UTC Keys path /parity/data/keys/MPDL
host2    | 2018-08-16 13:21:18 UTC DB path /parity/data/chains/MPDL/db/0796728f28a12423
host2    | 2018-08-16 13:21:18 UTC State DB configuration: fast
host2    | 2018-08-16 13:21:18 UTC Operating mode: active
host2    | 2018-08-16 13:21:18 UTC Configured for MPDL using AuthorityRound engine
host2    | 2018-08-16 13:21:23 UTC Public node URL: enode://49accab3db8be0bae061f3e160420b15e6b0509b44fa287bcf5d18f4f6c5a9c3c960edd31561af4747b88cdb6d491f4a40ddb84b55bfa44b29dbc5c38ed64c39@172.18.0.4:30303
host2    | 2018-08-16 13:21:53 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:22:23 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:22:53 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:23:20 UTC Imported #1 0xc51d…948a (0 txs, 0.00 Mgas, 0 ms, 0.57 KiB)
host3    | Loading config file from /parity/authority.toml
host3    | 2018-08-16 13:21:18 UTC Starting Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
host3    | 2018-08-16 13:21:18 UTC Keys path /parity/data/keys/MPDL
host3    | 2018-08-16 13:21:18 UTC DB path /parity/data/chains/MPDL/db/0796728f28a12423
host3    | 2018-08-16 13:21:18 UTC State DB configuration: fast
host3    | 2018-08-16 13:21:18 UTC Operating mode: active
host3    | 2018-08-16 13:21:18 UTC Configured for MPDL using AuthorityRound engine
host3    | 2018-08-16 13:21:23 UTC Public node URL: enode://57e3319313cd966a95e5a3f73b7f4954f88693ac36b7e4a46525dde705fe7aaa5be2e6736d60190e3289591f0c68916c887d675d2acb4ac10e8f500aea26b9f6@172.18.0.3:30303
host3    | 2018-08-16 13:21:53 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | 2018-08-16 13:22:23 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | 2018-08-16 13:22:53 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | Loading config file from /parity/authority.toml
host1    | 2018-08-16 13:21:19 UTC Starting Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
host1    | 2018-08-16 13:21:19 UTC Keys path /parity/data/keys/MPDL
host1    | 2018-08-16 13:21:19 UTC DB path /parity/data/chains/MPDL/db/0796728f28a12423
host1    | 2018-08-16 13:21:19 UTC State DB configuration: fast
host1    | 2018-08-16 13:21:19 UTC Operating mode: active
host1    | 2018-08-16 13:21:19 UTC Configured for MPDL using AuthorityRound engine
host1    | 2018-08-16 13:21:24 UTC Public node URL: enode://70f471330433ff3ab8d9461e00899d1be6b11c4c178f627d90d5a4b836e9fdbd27f1ab66a5bec5b335c189fabeeca819acf9baeff303af70b2a48b814ce2000d@172.18.0.2:30303
host1    | 2018-08-16 13:21:49 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:22:19 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:22:49 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:23:19 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | 2018-08-16 13:23:23 UTC    0/25 peers      9 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:23:23 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:23:24 UTC Imported #1 0x9438…7f20 (0 txs, 0.00 Mgas, 0 ms, 0.57 KiB)
host3    | 2018-08-16 13:23:28 UTC Imported #1 0x7f34…739d (0 txs, 0.00 Mgas, 0 ms, 0.57 KiB)
host1    | 2018-08-16 13:23:49 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | 2018-08-16 13:23:53 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:23:53 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:24:19 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | 2018-08-16 13:24:23 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:24:23 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:24:49 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host3    | 2018-08-16 13:24:53 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:24:53 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:25:19 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:25:20 UTC Imported #2 0xe996…a121 (0 txs, 0.00 Mgas, 2 ms, 0.57 KiB)
host3    | 2018-08-16 13:25:23 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:25:23 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:25:24 UTC Imported #2 0x6d46…12aa (0 txs, 0.00 Mgas, 0 ms, 0.57 KiB)
host3    | 2018-08-16 13:25:28 UTC Imported #2 0x8405…c039 (0 txs, 0.00 Mgas, 0 ms, 0.57 KiB)
host1    | 2018-08-16 13:25:49 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,   67 µs
host3    | 2018-08-16 13:25:53 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host2    | 2018-08-16 13:25:53 UTC    0/25 peers      9 KiB chain    8 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
host1    | 2018-08-16 13:26:05 UTC Blocked connection from parity://1.ui.parity using invalid token.
host1    | 2018-08-16 13:26:05 UTC Blocked connection to WebSockets server from untrusted origin: Some("parity://1.ui.parity")
host1    | 2018-08-16 13:26:05 UTC Blocked connection to WebSockets server from untrusted origin: Some("parity://1.ui.parity")
host1    | 2018-08-16 13:26:05 UTC Blocked connection from parity://1.ui.parity using invalid token.
host1    | 2018-08-16 13:26:05 UTC Blocked connection to WebSockets server from untrusted origin: Some("parity://1.ui.parity")
host1    | 2018-08-16 13:26:05 UTC Blocked connection from parity://1.ui.parity using invalid token.
host1    | 2018-08-16 13:26:05 UTC Blocked connection to WebSockets server from untrusted origin: Some("parity://1.ui.parity")
host1    | 2018-08-16 13:26:05 UTC Blocked connection to WebSockets server from untrusted origin: Some("parity://1.ui.parity")

The only hint is currently the UTC Blocked connection using invalid token. When I use the command to generate a new token, I receive the error: 

**Error generating token: Os { code: 2, kind: NotFound, message: "No such file or directory" }**

Please let me know if you need additional info.

**Comment by ddorgan** [comment]
Can you run the setup again and this time include --enable-client and see this displays a token.

Other than that, if you want to generate a token from within a container you should be sure to specify the correct toml configuration file, so it selects the right path.

**Comment by ddorgan** [comment]
@crossoveranx actually since the UI is being split out from the main codebase you may need to also download the parity ui / https://github.com/parity-js/shell

**Comment by crossoveranx** [comment]
@ddorgan 

I have tried both of your suggestions, however it still does not function:

client    | error: Found argument 'ui' which wasn't expected, or isn't valid in this context
client    |
client    | USAGE:
client    |     parity --ui-no-validation
client    |
client    | For more information try --help
client exited with code 1

Is the error I'm now receiving

**Comment by ddorgan** [comment]
Also there has been an update to remove the UI from parity-deploy, can you please checkout the latest master.

**Comment by ddorgan** [comment]
So with the latest master you should be able to connect to localhost:8545 via the parity-ui and not use the web based UI itself. Closing the ticket, let me know if you have any issues.
