### ISSUE TITLE
(FR) user defined parameters

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity-deploy#55]
At the moment I am [manually adding](https://github.com/paritytech/parity-ethereum/issues/9393#issuecomment-418285813)
```
--geth --jsonrpc-server-threads 100 --tx-queue-size 20000 --cache-size 4096 --tracing off --gas-floor-target 50000000 --pruning fast --tx-queue-mem-limit 0 --no-dapps --no-secretstore-http
```
to the resulting `docker-compose.yml` **after** running `./parity-deploy.sh --config aura --name myaura --nodes 4`

A new [CLI switch](https://github.com/paritytech/parity-deploy#cli-usage-options) could be useful, like 

```
NODEARGS="--geth --jsonrpc-server-threads 100 --tx-queue-size 20000 --cache-size 4096 --tracing off --gas-floor-target 50000000 --pruning fast --tx-queue-mem-limit 0 --no-dapps --no-secretstore-http"
./parity-deploy.sh --config aura --name myaura --nodes 4 --args $NODEARGS
docker-compose up
```

**Comment by drandreaskrueger** [comment]
workaround for now:  I have added those parameters [in all 4 files here](https://github.com/paritytech/parity-deploy/tree/master/config/docker).

So, feature request not indispensable, but ... nice-to-have.

**Comment by drandreaskrueger** [comment]
plus, one more file has to be changed, to almost never hit the gasLimit:

`parity-deploy/spec/genesis/aura`

to 40 million:
```
    "genesis": {
        "gasLimit": "0x2625A00"
    },
```

**Comment by ddorgan** [comment]
@drandreaskrueger can you just try adding all the extra options at the end of the parity-deploy.sh command ... 

e.g. 

```
parity-deploy.sh --config aura --nodes 4 --geth --jsonrpc-server-threads 100 --tx-queue-size 20000 --cache-size 4096 --tracing off --gas-floor-target 50000000 --pruning fast --tx-queue-mem-limit 0 --no-dapps --no-secretstore-http

```

I should maybe make this more clear in the README.

**Comment by drandreaskrueger** [comment]
ah, cool. Thanks.

**Comment by drandreaskrueger** [comment]
and the `gasLimit`? See https://github.com/paritytech/parity-deploy/issues/60

**Comment by ddorgan** [comment]
Issue resolved. Won't be updating the gasLimit.

**Comment by drandreaskrueger** [comment]
>  Won't be updating the gasLimit.

I see. What a pity. 

Then please consider this route to the same effect: https://github.com/paritytech/parity-deploy/issues/60

Thanks.

**Comment by ddorgan** [comment]
> I see. What a pity.

Let me have a look at updating the gasLimit, I'll include with the key generation changes.

**Comment by ddorgan** [comment]
@drandreaskrueger you can also add --gas-floor-target xxxxx at the end of the command line arguments for this by the way.

**Comment by ddorgan** [comment]
https://github.com/paritytech/parity-deploy/commit/0937ea2e221e31e7efc70f1e100afa038fe37d1e

**Comment by drandreaskrueger** [comment]
> Let me have a look at updating the gasLimit

hahaha, just seen, you simply [hardcoded 40 million now](https://github.com/paritytech/parity-deploy/commit/0937ea2e221e31e7efc70f1e100afa038fe37d1e#diff-f9890051b43f4ba212ec89cfda942988).

That is not what I meant. For for my one situation here, it is actually helpful, thanks.
