### ISSUE TITLE
millisecondTimestamp ?

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity-deploy#59]
How to configure [this](https://github.com/paritytech/parity-ethereum/issues/9468#issuecomment-419955626)? 

I have tried to turn https://github.com/paritytech/parity-deploy/blob/master/config/spec/engine/instantseal into

```
        "engine": {
                "instantSeal": {
                        "params": {
                                "millisecondTimestamp": true
                        }
                  }
        },

```
and then do

```
./parity-deploy.sh --config dev --name instantseal --geth
docker-compose up
```

but the time resolution is still whole seconds.

**Comment by drandreaskrueger** [comment]
Parity/v1.11.10-stable-31720e6-20180830

**Comment by ordian** [comment]
@drandreaskrueger this feature was [merged](https://github.com/paritytech/parity-ethereum/pull/9469) only 5 days ago, hence it's not in stable yet. Usually we backport only fixes, so you have to you use master branch if you want this feature enabled now.

**Comment by drandreaskrueger** [comment]
ah, gotcha - thanks.
