### ISSUE TITLE
ethkey not found

### ISSUE THREAD

**Issue by jarenal** [paritytech/parity-deploy#63]
Hi there,

I got the next error...

`./config/utils/keygen.sh: 5: ./config/utils/keygen.sh: ethkey: not found`

...when I execute the next command:

`./parity-deploy.sh --config aura --nodes 3 --ethstats`

I fulfill all the requirements:

1.  OpenSSL 1.0.2g  1 Mar 2016
2.  pip 18.0
3.  Docker version 18.06.1-ce, build e68fc7a
4.  docker-compose version 1.22.0, build f46880fe

I'm using Ubunt 16.04

Thank you.

**Comment by ddorgan** [comment]
Created PR: https://github.com/paritytech/parity-deploy/issues/63

Please check with the latest master.

**Comment by jarenal** [comment]
Works like a charm! 

Thanks for your quick response.

PS: Please update requirements in the README file.

**Comment by ddorgan** [comment]
https://github.com/paritytech/parity-deploy/commit/37b16b86d7638a45e6c788ea4a64bd2c4d1be8de

**Comment by ddorgan** [comment]
Updated README...
