### ISSUE TITLE
Can I use Parity UI for to connect to my private network?

### ISSUE THREAD

**Issue by jarenal** [paritytech/parity-deploy#65]
Hi,

I've setup successfully my private network using the next command:

`./parity-deploy.sh --config aura --nodes 3 --ethstats`

Everything looks ok through Etherstats Dashboard using the URL http://localhost:3001

After that, I've installed Parity UI from here...

[https://github.com/parity-js/shell](https://github.com/parity-js/shell)

...and when I try to connect request me enter a token using the next command:

`parity signer new-token`

My questions are:

- Can I use Parity UI for to connect to my private network?
- Where I should execute the command? `parity signer new-token`

Thanks in advance!

**Comment by ddorgan** [comment]
Ahhh this is now a bit more awkward with the UI being removed ..

Before you could pass the UI command which would output a token in the stdout. Now I think you'd need to exec into the docker container to run the command.

e.g. docker exec -ti <container id> bash  ... then run ``` /parity/parity --base-path /parity/data signer new-token ```

**Comment by ddorgan** [comment]
Any update on this?

**Comment by jarenal** [comment]
The command...

`/parity/parity --base-path /parity/data signer new-token`

...works like a charm, thank you.
