### ISSUE TITLE
keygen script forces linux architecture

### ISSUE THREAD

**Issue by jaybutera** [paritytech/parity-deploy#67]
Should be a simple fix but the script to install _ethkey_ in _./config/utils/keygen.sh_, installs the linux binary only.
```
ETHKEY_URL=`curl -sS "https://vanity-service.parity.io/parity-binaries?version=stable&format=markdown&os=linux&architecture=x86_64"
```

Should have an option to specify the different architectures and os types on the [server](https://vanity-service.parity.io/parity-binaries).

**Comment by ddorgan** [comment]
We only support linux, although yes I should detect architecture and use that. I'll open a PR for this.

**Comment by ddorgan** [comment]
https://github.com/paritytech/parity-deploy/pull/69
