### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/parity-deploy#84]
`./parity-deploy.sh --config aura`

```
threebody@deepin:~/Desktop/POA/parity-deploy$ docker-compose up -d
Starting 772123ad77a3_host1 ... error

ERROR: for 772123ad77a3_host1  Cannot start service host1: b'linux spec user: unable to find user parity: no matching entries in passwd file'

ERROR: for host1  Cannot start service host1: b'linux spec user: unable to find user parity: no matching entries in passwd file'
ERROR: Encountered errors while bringing up the project.
```

**Comment by ddorgan** [comment]
@jiangfuyao thanks for the report. Which distro (and version) are you using? I've not seen anything like this before...

**Comment by jiangfuyao** [comment]
`Parity-Ethereum/v2.0.4-beta-e2e1d22-20180910/x86_64-linux-gnu/rustc1.28.0`,
`parity-deploy is the last version.`

**Comment by ddorgan** [comment]
@jiangfuyao was wondering which operating system and specific version you are using. Thanks

**Comment by jiangfuyao** [comment]
deepin linux 15.7 Desktop.

**Comment by ddorgan** [comment]
@jiangfuyao can you double check you're using an up to date docker parity/parity:stable image for this. An issue which seems related was fixed some time back.

**Comment by ddorgan** [comment]
Closing...
