### ISSUE TITLE
Inconsistent nomenclature of chain spec

### ISSUE THREAD

**Issue by deanstef** [paritytech/parity-deploy#99]
I have studied the script and it looks amazing. However I have doubt regarding the configuration.

When the [authority.toml](https://github.com/paritytech/parity-deploy/blob/master/config/spec/authority_round.toml) file is generated, it specifies a chain = "/home/parity/chain.json". However, when the chain config is generated by the script, it is saved as spec.json (see [here](https://github.com/paritytech/parity-deploy/blob/master/parity-deploy.sh) on line 347). Indeed, by inspecting the docker container (assuming just one node within the network) there is an inconsistency. The authority.toml looks for a chain.json config file, while in that folder is present a spec.json config file. This can be deduce also by the mapping [host:container] in [docker services template](https://github.com/paritytech/parity-deploy/blob/master/config/docker/authority.yml)

**Comment by ddorgan** [comment]
@deanstef this was messing around to create the keys with the spec file. I have now removed this and am using ethstore and ethkey for all key activities.

Using the second spec file was removed: https://github.com/paritytech/parity-deploy/pull/104/files#diff-1b89a01090b9aa873cb0d3e5abb4a347L58 - Ok to close the issue?

**Comment by ddorgan** [comment]
Closing....
